### ISSUE TITLE
Problem with app_key

### ISSUE THREAD

**Issue by PedroMantovani** [vkaelin/LeagueStats#22]
good night friend, i cloned your project and i'm trying to run it on my computer but there is a certain "APP_KEY" in the .env file that i don't know what i put and when i try to run the project it ends up giving an error, it could help me

![image](https://user-images.githubusercontent.com/26251586/113363036-33adca80-9326-11eb-860a-29b8e59a47aa.png)

**Comment by vkaelin** [comment]
Hey 👋

You can just run the command ``node ace generate:key`` inside ``server`` folder and copy the value to your ``.env`` file !

**Comment by vkaelin** [comment]
Is it working @PedroMantovani ?

**Comment by vkaelin** [comment]
Closing this. Don't hesitate to ask if you have more questions.
