### ISSUE TITLE
How to support hero League China

### ISSUE THREAD

**Issue by AliYa-chen** [vkaelin/LeagueStats#36]
How to support hero League China

**Comment by vkaelin** [comment]
Hi! I'm not sure to understand, what's the Hero League China ?

**Comment by TonyTown6033** [comment]
Need CN summor search

**Comment by AliYa-chen** [comment]
> 嗨!我不太明白，中国英雄联盟是什么？

Need CN summor search

**Comment by vkaelin** [comment]
I'm using the official Riot API and sadly china is not available in it.

**Comment by vkaelin** [comment]
> I'm using the official Riot API and sadly china is not available in it.

Closing this as I can't do anything about the issue sadly.
