### ISSUE TITLE
I am studying hard on your project.

### ISSUE THREAD

**Issue by soulpam** [vkaelin/LeagueStats#39]
Hello.
I am studying hard on your project.
I will ask.

How can I find out the Match Tier?
Is there a way to get past match tiers?

**Comment by vkaelin** [comment]
Hi 👋

I'm not sure what you are looking for. The rank inside matches are fetched from the actual summoner rank. So if you are looking at an old match for the first time, the ranks may not be perfect.

**Comment by vkaelin** [comment]
Closing this. Don't hesitate to re-open if your question remains.
