### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by mahallemuhtari** [vkaelin/LeagueStats#4]
![Ekran Resmi 2020-03-08 14 28 00](https://user-images.githubusercontent.com/31033870/76161933-14effb00-6149-11ea-8255-490e800ba6d1.png)

![Ekran Resmi 2020-03-08 14 28 44](https://user-images.githubusercontent.com/31033870/76161938-22a58080-6149-11ea-800f-7ddca62ff56e.png)
![Ekran Resmi 2020-03-08 14 29 07](https://user-images.githubusercontent.com/31033870/76161945-30f39c80-6149-11ea-990b-f4dc83b62ded.png)

this problem i not solve pls help

**Comment by vkaelin** [comment]
We discussed about this issue on Discord. The issue was the Node.js version, it was too old to be able to use flags in Regex.
