### ISSUE TITLE
Detailed match data is not loading

### ISSUE THREAD

**Issue by DarkIntaqt** [vkaelin/LeagueStats#44]
See title for issue. Response of the match api is:
```json
{
    "message": "Cannot read properties of undefined (reading 'squarePortraitPath')"
}
```
Appears for the latest matches of my account: [Link](https://leaguestats.gg/summoner/euw/GGoE%20DarkIntaqt)

**Comment by vkaelin** [comment]
Thanks for creating the issue! It should be fixed! Don't hesitate to open a new issue if the issue is still here!
