### ISSUE TITLE
I can't search for RU server accounts

### ISSUE THREAD

**Issue by Suburbanno** [vkaelin/LeagueStats#84]
I can't search for RU server accounts

https://www.op.gg/summoners/ru/Бразильский-RUBR (working)
https://leaguestats.gg/summoner/ru/Бразильский-RUBR (no work)

![image](https://github.com/user-attachments/assets/21542bce-4943-4d54-892a-cdb87e3d9ce9)

**Comment by vkaelin** [comment]
Thanks for your issue!

It has been fixed by commit 2ee411cbef2b422d51b6cf483c385a1cd3b1e51d
