### ISSUE TITLE
[Bug] Co-op vs. AI is shown as Unknown gamemode

### ISSUE THREAD

**Issue by Suburbanno** [vkaelin/LeagueStats#87]
![image](https://github.com/user-attachments/assets/015812d0-13af-4f64-8d78-986f7d93dcd6)
![image](https://github.com/user-attachments/assets/0a089ea0-7ee8-4df2-ac14-63f628dbec26)

**Comment by vkaelin** [comment]
Thanks again for your issues!

Should be fixed by 5bd1c798e7610b1907338887dd5e9d2ec04eddb9
